#Universal
TIME:int = 30
#Rotation
MAX_SEC:int = 30
MAX_COL:int = 10
#Language
COMMAND_LANGUAGE = "cn"
DESCRIPTION = {
    "en": {
        #Main
        "GENERAL": "General commands.",
        "TEAMDPS": "Create and edit a team dps embed.",
        "ROTATION": "Create and edit a rotation.",
        "CHARACTER": "Create and edit a character.",
        #Stats
        "stats": "Stats",
        "hp": "HP",
        "atk": "ATK",
        "base atk": "Base ATK, including weapon",
        "def": "DEF",
        "em": "Elemental Mastery",
        "crate": "Critical Rate",
        "cdmg": "Critical Damage",
        "er": "Energy Recharge",
        "ele": "Elemental Damage",
        "heal": "Healing Bonus",
        "phys": "Physical Damage",
        #general commands
        "general help": "List commands.",
        "general help response": "There are four types of commands: `general`, `teamdps`, `rotation`, and `character`.",
        "general settings": "Change settings.",
        #teamdps commands
        "teamdps name": "name of the team",
        "teamdps description": "team description",
        "teamdps create": "Create team dps embed.",
        "teamdps create response": "You have created a team dps embed.",
        #rotation commands
        "rotation seconds": "# of seconds in the rotation",
        "rotation columns": "# of columns",
        "rotation description": "Character name and skills used",
        "rotation interval": "time interval in the format `startTime-endTime`",
        "rotation column": "# of column",
        "rotation create": "Create rotation",
        "rotation create response": "You have created the following rotation:",
        "rotation add": "Add to rotation",
        "rotation add response": "After adding an action:",
        "rotation remove": "Remove from rotation",
        "rotation remove response": "After removing an action:",
        "rotation addcol": "Add a column",
        "rotation addcol response": "After adding a column:",
        "rotation removecol": "Remove a column",
        "rotation removecol response": "After removing a column:",
        "rotation display": "Display your rotation",
        #character commands
        "character name": "Name of the character",
        "character description": "Describe the character",
        "character create": "Create character",
        "character create response": "You have created the character ",
        "character edit": "Edits character",
        "character edit response": "You have successfully changed the character ",
        "character list": "List all characters",
        "character list response": "Total characters: ",
        "character base": "Edit base stats of the character",
        "character base response": "You have added base stats for the character ",
        "character artifacts": "Edit artifact stats of the character (effective rolls)",
        "character artifacts response": "Adding artifact stats for the character ",
        "character percent": "Add percent of stats to the character",
        "character percent response": "You have added percent stats for the character ",
        "character flat": "Add flat stats to the character",
        "character flat response": "You have added flat stats for the character ",
        "character optcrit": "Optimize the crit stats of the character",
        "character optcrit response": "You have optimized the crit stats for the character ",
        "character energy": "Get the energy requirements of the character",
        "character burst": "amount of energy needed",
        "character onsame": "# of on-field same-element particles",
        "character offsame": "# of off-field same-element particles",
        "character ondiff": "# of on-field different-element particles",
        "character offdiff": "# of off-field different-element particles",
        "character onnone": "# of on-field no-element particles",
        "character offnone": "# of off-field no-element particles",
        "character fixed": "amount of fixed energy returned",
        "character current energy": "Current Energy",
        "character required energy": "Required Energy",
        #embeds
        "sec": "sec",
        "effective rolls": "effective rolls",
        "embedRotation": "Rotation Duration: ",
        "embedCharacter": "Description",
        #views
        "timeout": "The command has timed out",
        "language": "Language",
        "language response": "Received language settings",
        "color": "Color",
        "color response": "Received color settings",
        "red": "Red",
        "orange": "Orange",
        "yellow": "Yellow",
        "green": "Green",
        "aqua": "Aqua",
        "blue": "Blue",
        "violet": "Violet",
        "pink": "Pink",
        "sands": "Sands",
        "goblet": "Goblet",
        "hat": "Hat",
        "received": "Received "
    },
    "cn": {
        #Main
        "GENERAL": "通用指令",
        "TEAMDPS": "计算队伍dps",
        "ROTATION": "分配袖",
        "CHARACTER": "角色数据",
        #数据
        "stats": "数据",
        "hp": "生命值",
        "atk": "攻击力",
        "base atk": "基础攻击力（包括武器）",
        "def": "防御",
        "em": "元素精通",
        "crate": "暴击率",
        "cdmg": "暴击伤害",
        "er": "元素充能",
        "ele": "元素伤害",
        "heal": "治疗加成",
        "phys": "物理伤害",
        #general 指令
        "general help": "指令大全",
        "general help response": "指令被分为四种：`general`, `teamdps`, `rotation` `character`.",
        "general settings": "修改设置",
        #teamdps 指令
        "teamdps name": "队伍名称",
        "teamdps description": "队伍描述",
        "teamdps create": "制作队伍dps计算",
        "teamdps create response": "已开始制作队伍dps计算",
        #rotation 指令
        "rotation seconds": "几秒袖",
        "rotation columns": "几列数据",
        "rotation description": "角色名字与使用技能",
        "rotation interval": "时间`开局-结尾`",
        "rotation column": "列数",
        "rotation create": "制作袖",
        "rotation create response": "已开始排袖",
        "rotation add": "加",
        "rotation add response": "加入后",
        "rotation remove": "移除",
        "rotation remove response": "移除后",
        "rotation addcol": "加一列数据",
        "rotation addcol response": "加一列数据后",
        "rotation removecol": "移除一列数据",
        "rotation removecol response": "移除一列数据后",
        "rotation display": "查看袖",
        #character 指令
        "character name": "角色名称",
        "character description": "角色描述",
        "character create": "加入角色",
        "character create response": "已成功加入",
        "character edit": "修改角色数据",
        "character edit response": "已成功修改",
        "character list": "列出所有角色",
        "character list response": "角色数量：",
        "character base": "修改角色基础数据",
        "character base response": "已成功修改当前角色基础数据",
        "character artifacts": "修改角色圣遗物(请填入词条)",
        "character artifacts response": "已成功为当前角色加入圣遗物数据",
        "character percent": "修改其他百分比数据",
        "character percent response": "已成功为当前角色修改百分比数据",
        "character flat": "修改其他数据",
        "character flat response": "已成功为当前角色修改其他数据",
        "character optcrit": "配平双暴",
        "character optcrit response": "已成功为当前角色配平双暴",
        "character energy": "计算角色所需充能",
        "character burst": "所需能量",
        "character onsame": "前台同色",
        "character offsame": "后台同色",
        "character ondiff": "前台异色",
        "character offdiff": "后台异色",
        "character onnone": "前台无色",
        "character offnone": "后台无色",
        "character fixed": "固定回能",
        "character current energy": "当前充能",
        "character required energy": "所需充能",
        #embeds
        "sec": "秒",
        "effective rolls": "有效词条",
        "embedRotation": "袖（秒）：",
        "embedCharacter": "角色描述",
        #views
        "timeout": "指令已超时",
        "language": "语言",
        "language response": "已收到语言设置",
        "color": "颜色",
        "color response": "已收到颜色设置",
        "red": "红色",
        "orange": "橘色",
        "yellow": "黄色",
        "green": "绿色",
        "aqua": "青色",
        "blue": "蓝色",
        "violet": "紫色",
        "pink": "粉色",
        "sands": "沙漏",
        "goblet": "杯子",
        "hat": "帽子",
        "received": "已收到"
    }
}